### ISSUE TITLE
Rx.js Build Issues

### ISSUE THREAD

**Issue by kriscarle** [InspectorIT/DNN-Module-Template#2]
NuGet installs everything on first build and puts all of rx.js ts files into the /Scripts folder (instead of Scripts/Typings) creating duplicate errors in the build. To get around the issue I just deleted all references to Scripts\typings\rx.js\* in ModuleName.csproj and just let NuGet insert new TypeScriptCompile entries for rx.js when it installs. 

That seems to fix most of the issues. I was also seeing this issue https://github.com/borisyankov/DefinitelyTyped/issues/3081 and updated my rx.js versions to get their fix. I'd be happy to put together a pull request, but I figured I should let you know first. I'm not 100% sure I fixed this the right way.

Also, thanks for putting this template on GitHub, it is a huge help!

**Comment by jsheely** [comment]
Yes it seems that RxJS now ships with the TypeScript definition files directly in the nuget. So this makes the DefinitelyTyped file obsolete.

I've gone ahead and updated the solution to use TypeScript 1.4 and cleaned up the nuget packes. This should resolve the issue.

**Comment by kriscarle** [comment]
I tried to build with a fresh clone but now get errors saying it can't find the /Scripts and Scripts/Typings files. For some reason NuGet isn't installing the files into the Scripts folder. Any ideas why that would happen? From what I can tell it is supposed to... and yesterday it was overwriting them in that folder.

**Comment by jsheely** [comment]
I noticed that as well. I have a fix for it but haven't finished it. My goal is to remove the nuget package files from the GIT repo (/Scripts, /Content). But in something so the nuget package installer started acting up.

After running command

```
Update-Package -reinstall
```

a few times I was able to get it to work finally. Final fix is still in the works though.

**Comment by kriscarle** [comment]
That got it working again, thanks!
